'use client';

import { Activity, ArrowUpRight, BarChart3, Check, ChevronDown, CircleHelp, Database, Download, FlaskConical, Layers3, Play, Sparkles, Star, ThumbsDown, ThumbsUp, Upload } from 'lucide-react';
import { useMemo, useState } from 'react';

const rows = [
  ['MacBook Air M3', 'Exceeded every expectation. Quiet, quick, and the battery lasts all day.', 'Positive', '96.4%'],
  ['Echo Dot (5th Gen)', 'Sound is fine for its size, but it disconnects from Wi-Fi too often.', 'Negative', '89.1%'],
  ['Kindle Paperwhite', 'The screen is beautiful outdoors. Setup took about two minutes.', 'Positive', '94.8%'],
  ['Sony WH-1000XM5', 'Comfortable, though the touch controls can be a little temperamental.', 'Neutral', '67.2%'],
];
const samples = ['This is the best value I have found all year. Fast delivery too!', 'The product stopped working after a week. Very disappointed.', 'Looks exactly like the photos. It does what I need it to do.'];
function score(review: string) { const pos = /best|love|great|excellent|quick|beautiful|perfect|value|recommend|happy|exceeded/i.test(review); const neg = /disappointed|stopped|poor|bad|issue|disconnect|broken|worst|refund/i.test(review); return pos && !neg ? { label:'Positive', confidence:94.6, detail:'Strong positive language detected' } : neg && !pos ? { label:'Negative', confidence:91.2, detail:'Negative product experience detected' } : { label:'Neutral', confidence:68.9, detail:'Mixed or descriptive language detected' }; }

export default function Home() {
  const [review, setReview] = useState(samples[0]); const [classified, setClassified] = useState(true); const result = useMemo(() => score(review), [review]); const color = result.label.toLowerCase();
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span>sentilytics</span></div><nav className="header-nav" aria-label="Main navigation"><a className="nav-item active" href="#dashboard"><Activity size={16}/>Overview</a><a className="nav-item" href="#classify"><FlaskConical size={16}/>Classify review</a><a className="nav-item" href="#data"><Database size={16}/>Datasets <span className="nav-count">3</span></a><a className="nav-item" href="#models"><Layers3 size={16}/>Models</a><a className="nav-item" href="#insights"><BarChart3 size={16}/>Insights</a></nav><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={19}/></button><button className="export-btn"><Download size={16}/> Export report</button><div className="profile"><div className="avatar">AR</div><div><strong>Alex Rivera</strong><span>Data scientist</span></div><ChevronDown size={15}/></div></div></header>
    <section className="content">
      <div className="page-wrap" id="dashboard"><section className="intro-row"><div><p className="eyebrow">MODEL PERFORMANCE · LIVE</p><h1>Product review sentiment</h1><p className="subcopy">Classify customer feedback at scale with a Spark MLlib pipeline.</p></div><button className="upload-btn"><Upload size={16}/> Upload dataset</button></section>
        <section className="metric-grid" aria-label="Model metrics"><article className="metric-card"><span className="metric-icon teal"><Database size={20}/></span><div><p>Reviews processed</p><strong>2,847,221</strong><small><ArrowUpRight size={13}/> 12.4% this week</small></div></article><article className="metric-card"><span className="metric-icon purple"><Sparkles size={20}/></span><div><p>Model accuracy</p><strong>92.8%</strong><small className="plain">+1.6% vs. baseline</small></div></article><article className="metric-card"><span className="metric-icon amber"><Activity size={20}/></span><div><p>Avg. inference time</p><strong>84 ms</strong><small className="plain">per 1K reviews</small></div></article></section>
        <section className="dashboard-grid"><article className="panel classify-panel" id="classify"><div className="panel-heading"><div><p className="eyebrow">TRY THE MODEL</p><h2>Classify a review</h2></div><span className="model-chip"><span/> Logistic regression v2.4</span></div><label htmlFor="review-input">Paste a product review</label><textarea id="review-input" value={review} onChange={e=>{setReview(e.target.value);setClassified(false)}} placeholder="Write or paste a customer review..."/><div className="review-footer"><span>{review.length} / 1,000</span><button onClick={()=>setClassified(true)} className="classify-btn" disabled={!review.trim()}><Play size={15} fill="currentColor"/> Classify sentiment</button></div><div className={`prediction ${classified?'visible':''}`} aria-live="polite"><div className={`sentiment-badge ${color}`}>{result.label==='Positive'?<ThumbsUp size={17}/>:result.label==='Negative'?<ThumbsDown size={17}/>:<Activity size={17}/>} {result.label}</div><div className="confidence"><div><span>Confidence</span><strong>{result.confidence}%</strong></div><div className="progress"><span style={{width:`${result.confidence}%`}}/></div><p>{result.detail}</p></div></div><div className="quick-tests"><span>Try an example:</span>{samples.map((sample,i)=><button key={sample} onClick={()=>{setReview(sample);setClassified(true)}}><Star size={12}/> Review {i+1}</button>)}</div></article>
          <article className="panel distribution-panel" id="insights"><div className="panel-heading"><div><p className="eyebrow">DATASET SNAPSHOT</p><h2>Sentiment distribution</h2></div><button className="period">Last 30 days <ChevronDown size={14}/></button></div><div className="donut-wrap"><div className="donut"><div><strong>2.8M</strong><span>reviews</span></div></div><div className="legend"><p><i className="dot pos"/>Positive <b>68.4%</b></p><p><i className="dot neu"/>Neutral <b>18.7%</b></p><p><i className="dot neg"/>Negative <b>12.9%</b></p></div></div><div className="trend"><div><span>Daily volume</span><strong>+8.3%</strong></div><svg viewBox="0 0 360 68" preserveAspectRatio="none" aria-label="Rising review volume trend"><path d="M0 55 C22 47,28 57,48 44 S76 45,91 32 S116 44,132 35 S158 18,177 31 S203 25,220 18 S246 27,263 12 S289 23,310 8 S338 17,360 3" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 68 L0 55 C22 47,28 57,48 44 S76 45,91 32 S116 44,132 35 S158 18,177 31 S203 25,220 18 S246 27,263 12 S289 23,310 8 S338 17,360 3 L360 68Z"/></svg></div></article></section>
        <section className="panel table-panel" id="data"><div className="panel-heading"><div><p className="eyebrow">RECENT PREDICTIONS</p><h2>Review stream</h2></div><a href="#data">View all reviews <ArrowUpRight size={15}/></a></div><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>REVIEW</th><th>SENTIMENT</th><th>CONFIDENCE</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}><td><strong>{row[0]}</strong></td><td className="review-cell">{row[1]}</td><td><span className={`table-status ${row[2].toLowerCase()}`}>{row[2]}</span></td><td><b>{row[3]}</b></td></tr>)}</tbody></table></div></section>
        <footer><span><Check size={15}/> Pipeline healthy</span><span>Apache Spark 3.5.1 · MLlib</span><span>Last batch: 12 seconds ago</span></footer></div></section></main>;
}
