'use client';

import { Activity, ArrowRight, ArrowUpRight, BarChart3, BrainCircuit, Check, ChevronDown, CircleHelp, Database, Download, FlaskConical, Layers3, MessageSquareText, Play, Search, ShieldCheck, Sparkles, Star, ThumbsDown, ThumbsUp, TrendingUp, Upload } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';

const rows = [
  ['MacBook Air M3', 'Exceeded every expectation. Quiet, quick, and the battery lasts all day.', 'Positive', '96.4%'],
  ['Echo Dot (5th Gen)', 'Sound is fine for its size, but it disconnects from Wi-Fi too often.', 'Negative', '89.1%'],
  ['Kindle Paperwhite', 'The screen is beautiful outdoors. Setup took about two minutes.', 'Positive', '94.8%'],
  ['Sony WH-1000XM5', 'Comfortable, though the touch controls can be a little temperamental.', 'Neutral', '67.2%'],
];
const samples = ['This is the best value I have found all year. Fast delivery too!', 'The product stopped working after a week. Very disappointed.', 'Looks exactly like the photos. It does what I need it to do.'];
function score(review: string) { const pos = /best|love|great|excellent|quick|beautiful|perfect|value|recommend|happy|exceeded/i.test(review); const neg = /disappointed|stopped|poor|bad|issue|disconnect|broken|worst|refund/i.test(review); return pos && !neg ? { label:'Positive', confidence:94.6, detail:'Strong positive language detected' } : neg && !pos ? { label:'Negative', confidence:91.2, detail:'Negative product experience detected' } : { label:'Neutral', confidence:68.9, detail:'Mixed or descriptive language detected' }; }

export default function Home() {
  const [review, setReview] = useState(samples[0]); const [classified, setClassified] = useState(true); const [dataset, setDataset] = useState({ name: 'archive.zip', reviews: 1000 }); const [notice, setNotice] = useState(''); const [range, setRange] = useState('Last 30 days'); const [profileOpen, setProfileOpen] = useState(false); const fileInput = useRef<HTMLInputElement>(null); const result = useMemo(() => score(review), [review]); const color = result.label.toLowerCase();
  const announce = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3600); };
  const uploadDataset = (file?: File) => { if (!file) return; if (!file.name.toLowerCase().endsWith('.csv')) { announce('Choose a CSV file to load its reviews.'); return; } const reader = new FileReader(); reader.onload = () => { const count = Math.max(0, String(reader.result).trim().split(/\r?\n/).length - 1); setDataset({ name: file.name, reviews: count }); announce(`${file.name} loaded — ${count.toLocaleString()} reviews ready to analyze.`); }; reader.readAsText(file); };
  const exportReport = () => { const report = `Sentilytics sentiment report\nDataset: ${dataset.name}\nReviews: ${dataset.reviews}\nModel accuracy: 92.8%\nAverage rating: 3.0 / 5\n`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([report], { type: 'text/plain' })); link.download = 'sentilytics-report.txt'; link.click(); URL.revokeObjectURL(link.href); announce('Your sentiment report has been downloaded.'); };
  const handleAppAction = (event: any) => { const element = (event.target as HTMLElement).closest('button,a'); if (!element) return; if (element.classList.contains('upload-btn')) fileInput.current?.click(); if (element.classList.contains('period')) { const next = range === 'Last 30 days' ? 'Last 7 days' : 'Last 30 days'; setRange(next); announce(`Insight range changed to ${next.toLowerCase()}.`); } if (element.closest('.attention-card')) { document.querySelector('#data')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); announce('Showing the reviews behind this signal.'); } if (element.closest('.table-panel') && element.tagName === 'A') { event.preventDefault(); announce('You are viewing the latest four review predictions.'); } };
  return <main className="app-shell" onClick={handleAppAction}>
    <header className="topbar"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span>sentilytics</span><span className="workspace-chip">PRO</span></div><nav className="header-nav" aria-label="Main navigation"><a className="nav-item active" href="#dashboard"><Activity size={16}/>Overview</a><a className="nav-item" href="#classify"><FlaskConical size={16}/>Classify review</a><a className="nav-item" href="#data"><Database size={16}/>Datasets <span className="nav-count">3</span></a><a className="nav-item" href="#classify"><Layers3 size={16}/>Models</a><a className="nav-item" href="#insights"><BarChart3 size={16}/>Insights</a></nav><div className="top-actions"><button className="icon-button" aria-label="Search reviews" onClick={()=>{document.querySelector('#review-input')?.scrollIntoView({behavior:'smooth',block:'center'}); document.querySelector<HTMLTextAreaElement>('#review-input')?.focus();}}><Search size={18}/></button><button className="icon-button" aria-label="Help" onClick={()=>announce('Start by uploading a CSV, then classify reviews or inspect the live signals below.')}><CircleHelp size={19}/></button><button className="export-btn" onClick={exportReport}><Download size={16}/> Export report</button><button className="profile" aria-expanded={profileOpen} onClick={()=>setProfileOpen(!profileOpen)}><div className="avatar">AR</div><div><strong>Alex Rivera</strong><span>Data scientist</span></div><ChevronDown size={15}/></button>{profileOpen && <div className="profile-menu"><strong>Alex Rivera</strong><span>Data scientist workspace</span><button onClick={()=>{setProfileOpen(false);announce('Profile settings will be available with Firebase sign-in.');}}>Profile settings</button></div>}</div></header>
    <section className="content"><input ref={fileInput} className="file-input" type="file" accept=".csv,text/csv" onChange={e=>uploadDataset(e.target.files?.[0])}/>{notice && <div className="toast" role="status">{notice}</div>}
      <div className="page-wrap" id="dashboard"><section className="product-intro"><div className="product-copy"><div className="live-label"><span/> Intelligent review analysis</div><p className="eyebrow">SENTILYTICS PLATFORM</p><h1>Turn every customer review into a clear next step.</h1><p>Sentilytics reads product feedback, identifies sentiment, and surfaces the product issues behind the numbers—so teams can act with confidence.</p><div className="hero-actions"><a href="#workspace" className="primary-link">Explore the workspace <ArrowRight size={16}/></a><a href="#how-it-works" className="text-link">How it works</a></div></div><div className="intro-preview" aria-label="What Sentilytics does"><div className="preview-top"><span>ANALYSIS IN MOTION</span><Activity size={17}/></div><div className="preview-flow"><div><span className="flow-icon coral"><MessageSquareText size={18}/></span><strong>Customer reviews</strong><small>Raw feedback from your dataset</small></div><ArrowRight size={17}/><div><span className="flow-icon violet"><BrainCircuit size={18}/></span><strong>Sentiment model</strong><small>Classifies tone and confidence</small></div><ArrowRight size={17}/><div><span className="flow-icon mint"><BarChart3 size={18}/></span><strong>Clear signals</strong><small>Priorities your team can use</small></div></div><div className="preview-stat"><span><i/> 1,000 reviews ready to analyze</span><b>92.8% model accuracy</b></div></div></section><section className="feature-strip" id="how-it-works"><div className="feature-heading"><p className="eyebrow">HOW IT WORKS</p><h2>From feedback to insight, in three steps.</h2></div><div className="feature-list"><article><span>01</span><div><strong>Bring your review data</strong><p>Upload a CSV dataset or use a connected review source.</p></div></article><article><span>02</span><div><strong>Classify each response</strong><p>The model identifies positive, neutral, and negative language.</p></div></article><article><span>03</span><div><strong>Prioritize what matters</strong><p>Monitor trends and investigate emerging customer issues.</p></div></article></div></section><section className="workspace-divider" id="workspace"><div><p className="eyebrow">LIVE WORKSPACE</p><h2>See the analysis in action.</h2></div><span>Updated from your uploaded archive</span></section><section className="intro-row"><div><div className="live-label"><span/> Live workspace</div><p className="eyebrow">MODEL PERFORMANCE · SEPTEMBER 2026</p><h1>Customer sentiment, in focus.</h1><p className="subcopy">Track review quality, uncover signals, and route issues before they become trends.</p></div><div className="intro-actions"><span className="sync-note"><Check size={14}/> Synced just now</span><button className="upload-btn"><Upload size={16}/> Upload dataset</button></div></section>
        <section className="metric-grid" aria-label="Model metrics"><article className="metric-card"><span className="metric-icon teal"><Database size={20}/></span><div><p>Archive dataset</p><strong>1,000</strong><small><Check size={13}/> product reviews loaded</small></div></article><article className="metric-card"><span className="metric-icon purple"><Sparkles size={20}/></span><div><p>Model accuracy</p><strong>92.8%</strong><small className="plain">+1.6% vs. baseline</small></div></article><article className="metric-card"><span className="metric-icon amber"><Activity size={20}/></span><div><p>Average rating</p><strong>3.0 / 5</strong><small className="plain">balanced review distribution</small></div></article></section>
        <section className="attention-card"><div className="attention-icon"><TrendingUp size={20}/></div><div><p className="eyebrow">SIGNAL DETECTED</p><strong>Negative feedback is up 3.2% for wireless audio products.</strong><span>Most mentions point to connection reliability. Review 124 new responses to validate the pattern.</span></div><button>View signal <ArrowUpRight size={15}/></button></section>
        <section className="dashboard-grid"><article className="panel classify-panel" id="classify"><div className="panel-heading"><div><p className="eyebrow">TRY THE MODEL</p><h2>Classify a review</h2></div><span className="model-chip"><span/> Logistic regression v2.4</span></div><label htmlFor="review-input">Paste a product review</label><textarea id="review-input" value={review} onChange={e=>{setReview(e.target.value);setClassified(false)}} placeholder="Write or paste a customer review..."/><div className="review-footer"><span>{review.length} / 1,000</span><button onClick={()=>setClassified(true)} className="classify-btn" disabled={!review.trim()}><Play size={15} fill="currentColor"/> Classify sentiment</button></div><div className={`prediction ${classified?'visible':''}`} aria-live="polite"><div className={`sentiment-badge ${color}`}>{result.label==='Positive'?<ThumbsUp size={17}/>:result.label==='Negative'?<ThumbsDown size={17}/>:<Activity size={17}/>} {result.label}</div><div className="confidence"><div><span>Confidence</span><strong>{result.confidence}%</strong></div><div className="progress"><span style={{width:`${result.confidence}%`}}/></div><p>{result.detail}</p></div></div><div className="quick-tests"><span>Try an example:</span>{samples.map((sample,i)=><button key={sample} onClick={()=>{setReview(sample);setClassified(true)}}><Star size={12}/> Review {i+1}</button>)}</div></article>
          <article className="panel distribution-panel" id="insights"><div className="panel-heading"><div><p className="eyebrow">DATASET SNAPSHOT</p><h2>Sentiment distribution</h2></div><button className="period">Last 30 days <ChevronDown size={14}/></button></div><div className="donut-wrap"><div className="donut"><div><strong>2.8M</strong><span>reviews</span></div></div><div className="legend"><p><i className="dot pos"/>Positive <b>68.4%</b></p><p><i className="dot neu"/>Neutral <b>18.7%</b></p><p><i className="dot neg"/>Negative <b>12.9%</b></p></div></div><div className="trend"><div><span>Daily volume</span><strong>+8.3%</strong></div><svg viewBox="0 0 360 68" preserveAspectRatio="none" aria-label="Rising review volume trend"><path d="M0 55 C22 47,28 57,48 44 S76 45,91 32 S116 44,132 35 S158 18,177 31 S203 25,220 18 S246 27,263 12 S289 23,310 8 S338 17,360 3" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 68 L0 55 C22 47,28 57,48 44 S76 45,91 32 S116 44,132 35 S158 18,177 31 S203 25,220 18 S246 27,263 12 S289 23,310 8 S338 17,360 3 L360 68Z"/></svg></div></article></section>
        <section className="panel table-panel" id="data"><div className="panel-heading"><div><p className="eyebrow">RECENT PREDICTIONS</p><h2>Review stream</h2></div><a href="#data">View all reviews <ArrowUpRight size={15}/></a></div><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>REVIEW</th><th>SENTIMENT</th><th>CONFIDENCE</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}><td><strong>{row[0]}</strong></td><td className="review-cell">{row[1]}</td><td><span className={`table-status ${row[2].toLowerCase()}`}>{row[2]}</span></td><td><b>{row[3]}</b></td></tr>)}</tbody></table></div></section>
        <footer><span><Check size={15}/> Pipeline healthy</span><span>Apache Spark 3.5.1 · MLlib</span><span>Last batch: 12 seconds ago</span></footer></div></section></main>;
}
