'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDown, ArrowUpRight, Battery, Check, ChevronDown, Database, Headphones, Heart, Laptop, MessageSquareText, Search, Send, ShieldCheck, ShoppingBag, Sparkles, ThumbsDown, ThumbsUp, Watch } from 'lucide-react';

type Product = { id: string; name: string; category: string; price: string; icon: typeof Laptop; color: string; accent: string; description: string; rating: string; reviews: Review[] };
type Review = { id: number; author: string; initials: string; date: string; text: string; sentiment: 'Positive' | 'Negative'; confidence: number };
type DatasetReview = { id: string; product_id: string; user_id: string; rating: number; text: string; date: string };

const initialProducts: Product[] = [
  { id: 'macbook', name: 'MacBook Air M3', category: 'Computers', price: '$1,099', icon: Laptop, color: '#e9e6f5', accent: '#6358bc', description: 'Light on your bag. Big on everything else.', rating: '4.8', reviews: [{ id: 1, author: 'Olivia Bennett', initials: 'OB', date: 'Today', text: 'Incredibly fast and so light. The battery easily lasts my whole workday.', sentiment: 'Positive', confidence: 98 }, { id: 2, author: 'Marcus Chen', initials: 'MC', date: 'Yesterday', text: 'Beautiful display and a great keyboard. It feels like a real upgrade.', sentiment: 'Positive', confidence: 96 }, { id: 3, author: 'Priya Shah', initials: 'PS', date: 'Sep 18', text: 'Lovely laptop, but I wish it had more ports without carrying a hub.', sentiment: 'Negative', confidence: 72 }, { id: 4, author: 'Ethan Brooks', initials: 'EB', date: 'Sep 16', text: 'Quiet, quick, and the screen is gorgeous. Could not be happier.', sentiment: 'Positive', confidence: 97 }] },
  { id: 'headphones', name: 'Sony WH-1000XM5', category: 'Audio', price: '$349', icon: Headphones, color: '#e4edf3', accent: '#47748b', description: 'Your world, just the way you want to hear it.', rating: '4.6', reviews: [{ id: 5, author: 'Sofia Martinez', initials: 'SM', date: 'Today', text: 'Noise cancellation is fantastic on my commute. Super comfortable too.', sentiment: 'Positive', confidence: 97 }, { id: 6, author: 'Jordan Lee', initials: 'JL', date: 'Yesterday', text: 'The sound is lovely, but the touch controls are frustratingly unreliable.', sentiment: 'Negative', confidence: 93 }, { id: 7, author: 'Ava Wilson', initials: 'AW', date: 'Sep 19', text: 'The quality is poor and it broke quickly. Disappointed for the price.', sentiment: 'Negative', confidence: 99 }, { id: 8, author: 'Noah Kim', initials: 'NK', date: 'Sep 17', text: 'Wonderful sound, excellent battery, and I forget I am wearing them.', sentiment: 'Positive', confidence: 98 }] },
  { id: 'kindle', name: 'Kindle Paperwhite', category: 'Reading', price: '$159', icon: BookIcon, color: '#e8eee4', accent: '#5c7650', description: 'A little light for all the books you love.', rating: '4.7', reviews: [{ id: 9, author: 'Amelia Foster', initials: 'AF', date: 'Today', text: 'I have finished more books this month than all of last year. Love it.', sentiment: 'Positive', confidence: 98 }, { id: 10, author: 'Lucas Moore', initials: 'LM', date: 'Sep 20', text: 'The screen is easy on the eyes and the adjustable warmth is a dream.', sentiment: 'Positive', confidence: 97 }, { id: 11, author: 'Grace Park', initials: 'GP', date: 'Sep 18', text: 'Battery is amazing. Page turns can lag a little when it is cold out.', sentiment: 'Negative', confidence: 77 }] },
  { id: 'airpods', name: 'AirPods Pro (2nd gen)', category: 'Audio', price: '$249', icon: Headphones, color: '#f1e8e0', accent: '#9a684a', description: 'A sound experience you have to hear.', rating: '4.5', reviews: [{ id: 12, author: 'Mia Thompson', initials: 'MT', date: 'Today', text: 'They pair instantly and the sound quality is genuinely impressive.', sentiment: 'Positive', confidence: 96 }, { id: 13, author: 'Daniel Wright', initials: 'DW', date: 'Yesterday', text: 'The fit is perfect and transparency mode feels almost magical.', sentiment: 'Positive', confidence: 99 }, { id: 14, author: 'Chloe Davis', initials: 'CD', date: 'Sep 18', text: 'One earbud stopped charging after a few months. Not what I expected.', sentiment: 'Negative', confidence: 97 }] },
  { id: 'watch', name: 'Apple Watch Series 10', category: 'Wearables', price: '$399', icon: Watch, color: '#eee5e4', accent: '#a05b5e', description: 'Thinner. Smarter. A brilliant way to stay connected.', rating: '4.7', reviews: [{ id: 15, author: 'Isabella Clark', initials: 'IC', date: 'Today', text: 'The health features have helped me take better care of myself.', sentiment: 'Positive', confidence: 97 }, { id: 16, author: 'Benjamin Hall', initials: 'BH', date: 'Sep 20', text: 'Love the brighter display, but the battery barely makes it to bedtime.', sentiment: 'Negative', confidence: 94 }, { id: 17, author: 'Harper Allen', initials: 'HA', date: 'Sep 16', text: 'Fast, elegant, and surprisingly useful. My favorite upgrade in years.', sentiment: 'Positive', confidence: 97 }] },
  { id: 'bose', name: 'Bose QuietComfort Ultra', category: 'Audio', price: '$429', icon: Headphones, color: '#e6e8e2', accent: '#667365', description: 'Lose yourself in the music, not the noise.', rating: '4.6', reviews: [{ id: 18, author: 'Ella Mitchell', initials: 'EM', date: 'Today', text: 'The noise cancellation is incredible on long flights. So comfortable.', sentiment: 'Positive', confidence: 98 }, { id: 19, author: 'Ryan Patel', initials: 'RP', date: 'Sep 21', text: 'Great sound, but the app is confusing and the case feels too bulky.', sentiment: 'Negative', confidence: 88 }, { id: 20, author: 'Lily Cooper', initials: 'LC', date: 'Sep 18', text: 'Beautifully balanced audio. These are my favorite headphones.', sentiment: 'Positive', confidence: 97 }] },
  { id: 'ipad', name: 'iPad Air 11-inch', category: 'Tablets', price: '$599', icon: TabletIcon, color: '#e5ebf1', accent: '#577b9a', description: 'A brilliant canvas for work, play, and everything between.', rating: '4.7', reviews: [{ id: 21, author: 'Zoe Anderson', initials: 'ZA', date: 'Today', text: 'Light, fast, and perfect for sketching on the go. Love the display.', sentiment: 'Positive', confidence: 98 }, { id: 22, author: 'Oliver Reed', initials: 'OR', date: 'Sep 22', text: 'The screen is great, but storage fills up much too quickly.', sentiment: 'Negative', confidence: 90 }, { id: 23, author: 'Nina Garcia', initials: 'NG', date: 'Sep 19', text: 'Excellent performance and battery. It replaced my old laptop for travel.', sentiment: 'Positive', confidence: 97 }] },
  { id: 'dyson', name: 'Dyson V15 Detect', category: 'Home', price: '$749', icon: VacuumIcon, color: '#f0eadd', accent: '#a28048', description: 'Reveals the dust you never knew was there.', rating: '4.5', reviews: [{ id: 24, author: 'Mason Turner', initials: 'MT', date: 'Today', text: 'It picks up everything, even pet hair. Cleaning feels effortless now.', sentiment: 'Positive', confidence: 97 }, { id: 25, author: 'Layla Scott', initials: 'LS', date: 'Sep 21', text: 'Works well but it is heavy, and the battery does not last long enough.', sentiment: 'Negative', confidence: 95 }, { id: 26, author: 'Henry Adams', initials: 'HA', date: 'Sep 16', text: 'The laser shows every bit of dust. Excellent suction and easy to empty.', sentiment: 'Positive', confidence: 96 }] },
  { id: 'fujifilm', name: 'Fujifilm X100VI', category: 'Cameras', price: '$1,599', icon: CameraIcon, color: '#eee6e0', accent: '#956e5b', description: 'A little camera for the moments that matter.', rating: '4.8', reviews: [{ id: 27, author: 'Ruby Collins', initials: 'RC', date: 'Today', text: 'The colors are beautiful straight out of camera. I take it everywhere.', sentiment: 'Positive', confidence: 99 }, { id: 28, author: 'Theo Martin', initials: 'TM', date: 'Sep 20', text: 'Incredible image quality, but autofocus can be frustratingly slow.', sentiment: 'Negative', confidence: 94 }, { id: 29, author: 'Aria Lewis', initials: 'AL', date: 'Sep 17', text: 'A joy to use. Compact, sharp, and the film simulations are fantastic.', sentiment: 'Positive', confidence: 98 }] },
  { id: 'stanley', name: 'Stanley Quencher H2.0', category: 'Lifestyle', price: '$45', icon: BottleIcon, color: '#e3ede7', accent: '#57836b', description: 'Your hydration sidekick, wherever the day takes you.', rating: '4.6', reviews: [{ id: 30, author: 'Eva Brooks', initials: 'EB', date: 'Today', text: 'Keeps my water cold all day and fits in my car cup holder. Love it.', sentiment: 'Positive', confidence: 97 }, { id: 31, author: 'Jack Wilson', initials: 'JW', date: 'Sep 22', text: 'The handle is handy, but the lid leaks if it tips over in my bag.', sentiment: 'Negative', confidence: 92 }, { id: 32, author: 'Maya Patel', initials: 'MP', date: 'Sep 18', text: 'Great size and easy to clean. I actually drink enough water now.', sentiment: 'Positive', confidence: 96 }] },
];

function BookIcon({ size = 24, strokeWidth = 2 }: { size?: number; strokeWidth?: number }) { return <ShoppingBag size={size} strokeWidth={strokeWidth} />; }
function TabletIcon({ size = 24, strokeWidth = 2 }: { size?: number; strokeWidth?: number }) { return <Laptop size={size} strokeWidth={strokeWidth} />; }
function VacuumIcon({ size = 24, strokeWidth = 2 }: { size?: number; strokeWidth?: number }) { return <Battery size={size} strokeWidth={strokeWidth} />; }
function CameraIcon({ size = 24, strokeWidth = 2 }: { size?: number; strokeWidth?: number }) { return <Search size={size} strokeWidth={strokeWidth} />; }
function BottleIcon({ size = 24, strokeWidth = 2 }: { size?: number; strokeWidth?: number }) { return <Activity size={size} strokeWidth={strokeWidth} />; }

const API_BASE = process.env.NEXT_PUBLIC_REVIEWSENSE_API_URL ?? 'http://127.0.0.1:8000';

export default function Home() {
  const [products, setProducts] = useState(initialProducts);
  const [selectedId, setSelectedId] = useState(initialProducts[0].id);
  const [reviewText, setReviewText] = useState('');
  const [filter, setFilter] = useState<'All' | 'Positive' | 'Negative'>('All');
  const [notice, setNotice] = useState('');
  const [apiStatus, setApiStatus] = useState<'loading' | 'online' | 'offline'>('loading');
  const [datasetRows, setDatasetRows] = useState<DatasetReview[]>([]);
  const [datasetOffset, setDatasetOffset] = useState(0);
  const [datasetTotal, setDatasetTotal] = useState(0);
  const [datasetStatus, setDatasetStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const selected = products.find(product => product.id === selectedId)!;
  const positive = selected.reviews.filter(review => review.sentiment === 'Positive').length;
  const negative = selected.reviews.length - positive;
  const filteredReviews = useMemo(() => filter === 'All' ? selected.reviews : selected.reviews.filter(review => review.sentiment === filter), [filter, selected.reviews]);

  useEffect(() => {
    let active = true;
    fetch(`${API_BASE}/api/products`).then(response => {
      if (!response.ok) throw new Error('API unavailable');
      return response.json();
    }).then((apiProducts: Array<Partial<Product> & { id: string }>) => {
      if (!active) return;
      setProducts(current => current.map(local => {
        const remote = apiProducts.find(product => product.id === local.id);
        return remote ? { ...local, ...remote, icon: local.icon, color: local.color, accent: local.accent } as Product : local;
      }));
      setApiStatus('online');
    }).catch(() => { if (active) setApiStatus('offline'); });
    return () => { active = false; };
  }, []);

  useEffect(() => {
    let active = true;
    fetch(`${API_BASE}/api/dataset/reviews?offset=${datasetOffset}&limit=12`).then(response => {
      if (!response.ok) throw new Error('Dataset unavailable');
      return response.json();
    }).then((page: { total: number; reviews: DatasetReview[] }) => {
      if (!active) return;
      setDatasetRows(page.reviews);
      setDatasetTotal(page.total);
      setDatasetStatus('ready');
    }).catch(() => { if (active) setDatasetStatus('error'); });
    return () => { active = false; };
  }, [datasetOffset]);

  async function submitReview(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const text = reviewText.trim();
    if (!text) return;
    try {
      const response = await fetch(`${API_BASE}/api/products/${selectedId}/reviews`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) });
      if (!response.ok) throw new Error('Review could not be saved. Please try again.');
      const entry: Review = await response.json();
      setProducts(current => current.map(product => product.id === selectedId ? { ...product, reviews: [entry, ...product.reviews] } : product));
      setReviewText(''); setFilter('All'); setNotice(`Review analyzed as ${entry.sentiment.toLowerCase()} and saved for ${selected.name}.`);
      window.setTimeout(() => setNotice(''), 4200);
    } catch {
      setApiStatus('offline');
      setNotice('Cannot reach the ReviewSense backend. Start it with: python -m uvicorn backend.main:app --reload --port 8000');
    }
  }

  return <main className="rs-app">
    <header className="rs-topbar"><a href="#home" className="rs-brand"><span className="rs-brand-icon"><Sparkles size={17}/></span><span>review<span className="rs-brand-light">sense</span></span></a><nav className="rs-nav"><a className="selected" href="#home">Discover</a><a href="#product-detail">Products</a><a href="#review-list">Reviews</a></nav><div className="rs-top-right"><span className={`rs-model-status ${apiStatus}`}><i/> {apiStatus === 'online' ? 'Model online' : apiStatus === 'loading' ? 'Connecting…' : 'Backend offline'}</span><button className="rs-avatar" aria-label="Your profile">JD</button></div></header>

    <section className="rs-hero" id="home"><div className="rs-hero-inner"><div className="rs-hero-copy"><div className="rs-overline"><span/> THE GOOD, THE BAD &amp; THE HONEST</div><h1>Find your next<br/> <em>favorite thing.</em></h1><p>Real opinions, thoughtfully understood. Explore honest customer experiences before you make it yours.</p><a href="#product-detail" className="rs-hero-cta">Explore the collection <ArrowDown size={15}/></a></div><div className="rs-hero-art" aria-label="Featured headphones and customer rating"><div className="rs-art-halo"/><div className="rs-art-card"><span className="rs-art-label">THE LISTENER'S PICK</span><div className="rs-headphone-illustration"><Headphones size={128} strokeWidth={1.1}/><span className="rs-art-sparkle">✳</span></div><strong>Sony WH-1000XM5</strong><span className="rs-art-rating"><span>★★★★★</span> &nbsp; 4.6 <small>(248 reviews)</small></span></div><div className="rs-float-note"><span className="rs-float-icon"><Heart size={15} fill="currentColor"/></span><span><b>Loved by listeners</b><small>94% positive sentiment</small></span></div><div className="rs-float-stat"><strong>4.8<span>/5</span></strong><small>community rating</small></div></div></div></section>

    <section className="rs-collection" id="product-detail"><div className="rs-section-top"><div><div className="rs-kicker">THE COLLECTION <span>·</span> 10 PRODUCTS</div><h2>A few things worth talking about.</h2><p>Pick a product to hear what people really think.</p></div><button className="rs-sort">Most loved <ChevronDown size={15}/></button></div>
      <div className="rs-product-grid">{products.map(product => { const Icon = product.icon; const score = Math.round(product.reviews.filter(review => review.sentiment === 'Positive').length / product.reviews.length * 100); return <button className={`rs-product-card ${selectedId === product.id ? 'active' : ''}`} key={product.id} onClick={() => { setSelectedId(product.id); setFilter('All'); }} aria-pressed={selectedId === product.id}><span className="rs-product-photo" style={{ '--product-bg': product.color, '--product-accent': product.accent } as React.CSSProperties}><span className="rs-product-shape"><Icon size={42} strokeWidth={1.2}/></span><span className="rs-product-score"><Heart size={11} fill="currentColor"/> {score}%</span></span><span className="rs-product-info"><span className="rs-product-meta">{product.category}<b>{product.price}</b></span><strong>{product.name}</strong><span className="rs-product-rating"><span>★★★★★</span> {product.rating} <small>· {product.reviews.length} reviews</small></span></span></button>; })}</div>

      <div className="rs-detail-heading"><div><div className="rs-kicker">THE COMMUNITY SAYS</div><h2>On the record.</h2><p>Every review, one honest conversation.</p></div><span className="rs-selected-product"><span className="rs-mini-icon" style={{ background: selected.color, color: selected.accent }}><selected.icon size={17}/></span><span><b>{selected.name}</b><small>{selected.description}</small></span><span className="rs-selected-rating">★ {selected.rating}</span></span></div>

      <div className="rs-dashboard"><section className="rs-reviews-panel" id="review-list"><div className="rs-reviews-head"><div><h3>Customer reviews <span>{selected.reviews.length}</span></h3><p>What verified buyers are saying</p></div><div className="rs-filters" aria-label="Filter reviews">{(['All', 'Positive', 'Negative'] as const).map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
          <div className="rs-review-list">{filteredReviews.length ? filteredReviews.map(review => <article className="rs-review" key={review.id}><span className={`rs-review-avatar avatar-${review.initials.charCodeAt(0) % 5}`}>{review.initials}</span><div className="rs-review-main"><div className="rs-review-top"><div><b>{review.author}</b><span className="rs-verified"><ShieldCheck size={12}/> Verified buyer</span></div><time>{review.date}</time></div><p>{review.text}</p><div className="rs-review-bottom"><span className={`rs-sentiment ${review.sentiment.toLowerCase()}`}>{review.sentiment === 'Positive' ? <ThumbsUp size={12}/> : <ThumbsDown size={12}/>} {review.sentiment}</span><span className="rs-confidence">Model confidence <b>{review.confidence}%</b></span></div></div></article>) : <div className="rs-empty">No {filter.toLowerCase()} reviews yet. Be the first to share one.</div>}</div>
          <form className="rs-write-review" onSubmit={submitReview}><div className="rs-write-label"><span className="rs-write-icon"><MessageSquareText size={16}/></span><span><b>Your experience matters.</b><small>Share an honest review of this product.</small></span></div><textarea aria-label="Write a product review" maxLength={500} value={reviewText} onChange={event => setReviewText(event.target.value)} placeholder="What did you love? What could be better?"/><div className="rs-compose-footer"><span>{reviewText.length}/500</span><button type="submit" disabled={!reviewText.trim() || apiStatus !== 'online'}><Send size={14}/> {apiStatus === 'loading' ? 'Connecting…' : apiStatus === 'offline' ? 'Backend offline' : 'Submit review'}</button></div></form>
        </section>

        <aside className="rs-insights"><div className="rs-insights-head"><span className="rs-insights-icon"><Activity size={17}/></span><span><b>Sentiment snapshot</b><small>What the community feels</small></span><button aria-label="More sentiment insights"><ArrowUpRight size={16}/></button></div><div className="rs-chart-title"><span>OVERALL MOOD</span><strong>{Math.round(positive / Math.max(selected.reviews.length, 1) * 100)}% <small>positive</small></strong></div><div className="rs-donut-row"><div className="rs-donut" style={{ '--positive-share': `${positive / Math.max(selected.reviews.length, 1) * 100}%` } as React.CSSProperties}><div><strong>{selected.reviews.length}</strong><span>reviews</span></div></div><div className="rs-legend"><div><i className="positive-dot"/><span>Positive</span><b>{positive}</b></div><div><i className="negative-dot"/><span>Negative</span><b>{negative}</b></div></div></div><div className="rs-bar-list"><div className="rs-bar-row"><span>Positive</span><div><i className="positive-bar" style={{ width: `${positive / Math.max(selected.reviews.length, 1) * 100}%` }}/></div><b>{Math.round(positive / Math.max(selected.reviews.length, 1) * 100)}%</b></div><div className="rs-bar-row"><span>Negative</span><div><i className="negative-bar" style={{ width: `${negative / Math.max(selected.reviews.length, 1) * 100}%` }}/></div><b>{Math.round(negative / Math.max(selected.reviews.length, 1) * 100)}%</b></div></div><div className="rs-ai-note"><span><Sparkles size={14}/></span><p><b>A little perspective</b><br/>{positive > negative ? 'Most owners are enjoying this one. ' : 'Some owners have raised concerns. '} Based on {selected.reviews.length} community {selected.reviews.length === 1 ? 'review' : 'reviews'}.</p></div><div className="rs-powered"><span><span className="rs-powered-mark"><Sparkles size={11}/></span> Thoughtfully analyzed by <b>ReviewSense AI</b></span><span className="rs-live-dot"/></div></aside></div>

      <section className="rs-dataset" id="training-data"><div className="rs-dataset-heading"><div><div className="rs-kicker">MODEL INPUT <span>·</span> CSV ARCHIVE</div><h2>Training dataset</h2><p>Browse the original reviews used to teach the sentiment model.</p></div><span className="rs-dataset-count"><Database size={14}/>{datasetTotal.toLocaleString()} reviews</span></div><div className="rs-dataset-note">Source labels are kept as provided: Product_A to Product_E. These are training data IDs and are not linked to the named products above. The original 1–5 star rating is shown for each record.</div>{datasetStatus === 'loading' ? <div className="rs-dataset-state">Loading dataset reviews…</div> : datasetStatus === 'error' ? <div className="rs-dataset-state">The dataset is unavailable. Check that the ReviewSense API is running.</div> : <><div className="rs-dataset-list">{datasetRows.map(row => <article className="rs-dataset-row" key={row.id}><span className="rs-dataset-product">{row.product_id.replace('_', ' ')}</span><div className="rs-dataset-review"><p>{row.text}</p><span>{row.id} <i>·</i> {row.user_id}</span></div><span className="rs-dataset-rating" aria-label={`${row.rating} out of 5 stars`}>{Array.from({ length: 5 }, (_, index) => <i className={index < row.rating ? 'filled' : ''} key={index}>★</i>)}</span><time>{row.date}</time></article>)}</div><div className="rs-dataset-pagination"><span>Showing {datasetOffset + 1}–{Math.min(datasetOffset + datasetRows.length, datasetTotal)} of {datasetTotal.toLocaleString()}</span><div><button disabled={datasetOffset === 0} onClick={() => setDatasetOffset(Math.max(0, datasetOffset - 12))}>Previous</button><span>Page {Math.floor(datasetOffset / 12) + 1} of {Math.ceil(datasetTotal / 12)}</span><button disabled={datasetOffset + 12 >= datasetTotal} onClick={() => setDatasetOffset(datasetOffset + 12)}>Next</button></div></div></>}</section>
      {notice && <div className="rs-toast" role="status"><Check size={16}/>{notice}</div>}
    </section><footer className="rs-footer"><a href="#home" className="rs-brand"><span className="rs-brand-icon"><Sparkles size={14}/></span><span>review<span className="rs-brand-light">sense</span></span></a><span>Good decisions start with honest reviews.</span><span>© 2026 ReviewSense</span></footer>
  </main>;
}
